# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [3]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [4]:
# a =
a = pd.Series([ 100, 200, 300, 400])

Print a, and data type

In [5]:
print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

Using indexing access the element 300 from the series a.

In [6]:

print(a[2])

300

What are the values of index for series a?

In [7]:
a.index

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [8]:
a.index=['c','a','b','d']

Access the value in the series with index 'd'

In [9]:
print(a['d'])

400

Sort the values wrt to the index and print it

In [10]:
a.sort_index()

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [11]:
b = pd.Series([800,450,100],index=['e','f','g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [12]:
a = pd.concat([a,b])

In [13]:
#print a again after appending b into it
a

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [14]:
a = a.sort_values(ascending=False)
print(a.index)

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [15]:
df = pd.DataFrame(a)

In [16]:
print(df)

     0
e  800
f  450
d  400
b  300
a  200
c  100
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [17]:
df.shape

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [18]:
# yep its same as the series.
df.index

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [19]:
print(df.head())
print(df.tail())

     0
e  800
f  450
d  400
b  300
a  200
     0
d  400
b  300
a  200
c  100
g  100

Rename the column of the dataframe as 'points'

In [20]:
df.columns=['points']

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [21]:
#Create fruits array

fruits = np.random.choice(['orange','mango','apple'],7)
fruits

array(['apple', 'orange', 'mango', 'apple', 'mango', 'mango', 'mango'],
      dtype='<U6')

In [22]:
#Create series fruits out of fruits array

fruits = pd.Series(fruits)
fruits

0     apple
1    orange
2     mango
3     apple
4     mango
5     mango
6     mango
dtype: object

Change the index of fruits to the index of dataframe df

In [23]:
fruits.index=df.index
fruits

e     apple
f    orange
d     mango
b     apple
a     mango
c     mango
g     mango
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [24]:
df['fruits']=fruits
df.head()

   points  fruits
e     800   apple
f     450  orange
d     400   mango
b     300   apple
a     200   mango

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [25]:
d1 =pd.DataFrame({'city' : ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
                  'Temperature' : [15, 22, 20, 26,-2]})

Print(d1)

In [26]:
d1

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [27]:
d1.shape

(5, 2)

Set city = d1['city']

In [28]:
city=d1['city']

print city <br>
What is the type of city.

In [29]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [30]:
d2 =pd.DataFrame({'city':['Bengalaru','Coimbatore','Srirangam','Pondicherry'],'Temperature':[24,35,36,39]})

print the shape of this dataframe

In [31]:
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [32]:
d3 = pd.concat([d1,d2],ignore_index=True)
d3

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
5    Bengalaru           24
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [33]:
d3[d3['Temperature']<=20][['city']]

         city
0  Chandigarh
2      Kanpur
4      Manali

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [34]:
d3[d3['Temperature']>=35][['city']]

          city
6   Coimbatore
7    Srirangam
8  Pondicherry

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [40]:
# write function here

def is_ut(x):

#     # write code below
  if x in ['Chandigarh','Pondicherry','Delhi']:
    return True
  else:
    return False
d3['is_ut'] = d3['city'].apply(is_ut)

In [41]:
# print d3
d3

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
5    Bengalaru           24  False
6   Coimbatore           35  False
7    Srirangam           36  False
8  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [44]:
# write function here
def c_to_f(x):
  return (x*(9/5))+32

In [45]:
# check function c_to_f(10)
c_to_f(10)

50.0

In [48]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'
d3['temp_farenhiet']=d3['Temperature'].apply(c_to_f)

d3

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
2       Kanpur           20  False            68.0
3      Chennai           26  False            78.8
4       Manali           -2  False            28.4
5    Bengalaru           24  False            75.2
6   Coimbatore           35  False            95.0
7    Srirangam           36  False            96.8
8  Pondicherry           39   True           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [55]:
d1[d3['is_ut'] == True]

/tmp/ipykernel_1092/3170152090.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  d1[d3['is_ut'] == True]

         city  Temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [57]:
d1[d3['temp_farenhiet']>90]


# as there are no cities having temperature greater than 90F so it displays nothing

/tmp/ipykernel_1092/3656515490.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  d1[d3['temp_farenhiet']>90]

Empty DataFrame
Columns: [city, Temperature]
Index: []

Select only the first three rows of the dataframe d1.

In [164]:
d1.head(3)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [66]:
d3.iloc[:,-2:]

   is_ut  temp_farenhiet
0   True            59.0
1   True            71.6
2  False            68.0
3  False            78.8
4  False            28.4
5  False            75.2
6  False            95.0
7  False            96.8
8   True           102.2

## Groupby

In [187]:
# Create a dataframe using dictionary of your choice

data = pd.DataFrame({'Names': ['John','Sam','Tony','Natasha','Grace','Raman','Rekha','Alen','Alex','Alena'],
                     'Subject':['English','Math','Math','Science','English','Science','English','Math','Math','Math'],
                     'Paper':[2,1,1,1,1,2,1,2,2,1],
                     'Marks':[80,75,90,87,65,76,55,90,87,66]})
data

     Names  Subject  Paper  Marks
0     John  English      2     80
1      Sam     Math      1     75
2     Tony     Math      1     90
3  Natasha  Science      1     87
4    Grace  English      1     65
5    Raman  Science      2     76
6    Rekha  English      1     55
7     Alen     Math      2     90
8     Alex     Math      2     87
9    Alena     Math      1     66

In [188]:
# Use Groupby of single column with aggregate sum()
data.groupby(['Subject'])['Marks'].sum()

Subject
English    200
Math       408
Science    163
Name: Marks, dtype: int64

In [189]:
# Use Groupby of single column with aggregate count()
data.groupby('Subject')['Subject'].count()

Subject
English    3
Math       5
Science    2
Name: Subject, dtype: int64

In [190]:
# Use Groupby of single column with aggregate min() and max()
data.groupby('Subject')['Marks'].agg(['min','max'])

         min  max
Subject
English   55   80
Math      66   90
Science   76   87

In [193]:
# Use Groupby of any 2 columns with aggregate mean()
data.groupby(['Subject','Paper'])['Marks'].mean()

Subject  Paper
English  1        60.0
         2        80.0
Math     1        77.0
         2        88.5
Science  1        87.0
         2        76.0
Name: Marks, dtype: float64

In [195]:
# Use Groupby of any 2 columns with aggregate min() and max()
data.groupby(['Subject','Paper'])['Marks'].agg(['min','max'])

               min  max
Subject Paper
English 1       55   65
        2       80   80
Math    1       66   90
        2       87   90
Science 1       87   87
        2       76   76

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [27]:
# a =
a=pd.date_range(start='2020-01-01',end='2021-04-01')

print a

In [28]:
a

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [29]:
print(len(a))

457

What is the type of a?

In [30]:
print(type(a))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>